### ISSUE TITLE
Fix organizations with spaces

### ISSUE THREAD

**Issue by nikkitashl** [SOURC3XYZ/sourc3#153] opened 2022-07-06 07:16 UTC
When organization created with spaces, part after space is truncated

**Comment by nikkitashl** [comment] 2022-07-12 10:47
Must be done in UI. Shader arguments with names must be placed inside `""`

**Comment by SixStringer91** [comment] 2022-07-17 18:12
done

**Comment by kovaletskaterina** [comment] 2022-07-21 10:06
Closed as duplicate of https://github.com/SOURC3XYZ/sourc3/issues/148

**Closed by kovaletskaterina** 2022-07-21 10:06 UTC
Labels: bug, dapp
